### ISSUE TITLE
Reason of failure

### ISSUE THREAD

**Issue by ghost** [arghyadeep-k/deno-password-checker#1]
Hello, I think it would be great if we could have access to the reason of failure. For instance "password must be longer than x characters", "password must contain at least one special character" and so on.

We could change the return type of `checkPassword` to something along the lines of

```typescript
interface VerificationResult {
  isValid: boolean,
  reason: string?
}
```

Maybe we don't want to change the `checkPassword` spec, in this case we could create a function `checkPasswordWithResult` or something like that.

What do you think about it? I can make a PR if you like the idea.

**Comment by arghyadeep-k** [comment]
I like the idea as long as we keep the original function intact and create a separate function.

Feel free to work on it if you want and submit a PR to the `dev` branch. 
Assigned this issue to you.
